const assetUrl = (path) => `${import.meta.env.BASE_URL}${path}`;

export const PLATFORMS = {
  GITHUB: {
    id: "github",
    label: "Github",
    icon: assetUrl("images/platform/icon-github.svg"),
    bgColor: "#1A1A1A",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.github.com/john-doe",
    urlPattern: /^https:\/\/(www\.)?github\.com\/[A-Za-z0-9-]+\/?$/,
    errorMessage: "Must be a valid GitHub profile URL",
  },
  FRONTEND_MENTOR: {
    id: "frontend_mentor",
    label: "Frontend Mentor",
    icon: assetUrl("images/platform/icon-frontend-mentor.svg"),
    bgColor: "#FFFFFF",
    textColor: "#0E0E0E",
    placeholder: "e.g. https://www.frontendmentor.io/profile/john-doe",
    urlPattern:
      /^https:\/\/(www\.)?frontendmentor\.io\/profile\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid Frontend Mentor profile URL",
  },
  TWITTER: {
    id: "twitter",
    label: "Twitter / X",
    icon: assetUrl("images/platform/icon-twitter.svg"),
    bgColor: "#43B7E9",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.twitter.com/john_doe",
    urlPattern: /^https:\/\/(www\.)?(twitter|x)\.com\/[A-Za-z0-9_]+\/?$/,
    errorMessage: "Must be a valid Twitter/X profile URL",
  },
  LINKEDIN: {
    id: "linkedin",
    label: "LinkedIn",
    icon: assetUrl("images/platform/icon-linkedin.svg"),
    bgColor: "#2D68C4",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.linkedin.com/in/john-doe",
    urlPattern: /^https:\/\/(www\.)?linkedin\.com\/in\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid LinkedIn profile URL",
  },
  YOUTUBE: {
    id: "youtube",
    label: "YouTube",
    icon: assetUrl("images/platform/icon-youtube.svg"),
    bgColor: "#EE3939",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.youtube.com/@john-doe",
    urlPattern:
      /^https:\/\/(www\.)?youtube\.com\/(\@[A-Za-z0-9_.-]+|channel\/[A-Za-z0-9_-]+|c\/[A-Za-z0-9_.-]+|user\/[A-Za-z0-9_.-]+)\/?$/,
    errorMessage: "Must be a valid YouTube channel or handle URL",
  },
  FACEBOOK: {
    id: "facebook",
    label: "Facebook",
    icon: assetUrl("images/platform/icon-facebook.svg"),
    bgColor: "#2442AC",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.facebook.com/@john-doe",
    placeholder: "e.g. https://www.facebook.com/john-doe",
    urlPattern: /^https:\/\/(www\.)?facebook\.com\/[A-Za-z0-9.]+\/?$/,
    errorMessage: "Must be a valid Facebook profile URL",
  },
  TWITCH: {
    id: "twitch",
    label: "Twitch",
    icon: assetUrl("images/platform/icon-twitch.svg"),
    bgColor: "#EE3FC8",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.twitch.com/@john-doe",
    placeholder: "e.g. https://www.twitch.tv/john-doe",
    urlPattern: /^https:\/\/(www\.)?twitch\.tv\/[A-Za-z0-9_]+\/?$/,
    errorMessage: "Must be a valid Twitch profile URL",
  },
  DEVTO: {
    id: "devto",
    label: "Dev.to",
    icon: assetUrl("images/platform/icon-devto.svg"),
    bgColor: "#333333",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://dev.to/john-doe",
    urlPattern: /^https:\/\/dev\.to\/[A-Za-z0-9_-]+\/?$/,
    errorMessage: "Must be a valid Devto profile URL",
  },
  CODEWARS: {
    id: "codewars",
    label: "Codewars",
    icon: assetUrl("images/platform/icon-codewars.svg"),
    bgColor: "#8A1A50",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.codewars.com/users/john-doe",
    urlPattern: /^https:\/\/(www\.)?codewars\.com\/users\/[A-Za-z0-9_-]+\/?$/,
    errorMessage: "Must be a valid Codewars profile URL",
  },
  CODEPEN: {
    id: "codepen",
    label: "CodePen",
    icon: assetUrl("images/platform/icon-codepen.svg"),
    bgColor: "#47CF73",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://codepen.io/john-doe",
    urlPattern: /^https:\/\/(www\.)?codepen\.io\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid CodePen profile URL",
  },
  FREECODECAMP: {
    id: "freecodecamp",
    label: "freeCodeCamp",
    icon: assetUrl("images/platform/icon-freecodecamp.svg"),
    bgColor: "#30226B",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://www.freecodecamp.org/john-doe",
    urlPattern: /^https:\/\/(www\.)?freecodecamp\.org\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid freeCodeCamp profile URL",
  },
  GITLAB: {
    id: "gitlab",
    label: "GitLab",
    icon: assetUrl("images/platform/icon-gitlab.svg"),
    bgColor: "#EB4925",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://gitlab.com/john-doe",
    urlPattern: /^https:\/\/(www\.)?gitlab\.com\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid GitLab profile URL",
  },
  HASHNODE: {
    id: "hashnode",
    label: "Hashnode",
    icon: assetUrl("images/platform/icon-hashnode.svg"),
    bgColor: "#2962FF",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://hashnode.com/@john-doe",
    urlPattern: /^https:\/\/(www\.)?hashnode\.com\/@[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid Hashnode profile URL",
  },
  STACK_OVERFLOW: {
    id: "stack_overflow",
    label: "Stack Overflow",
    icon: assetUrl("images/platform/icon-stack-overflow.svg"),
    bgColor: "#EC7100",
    textColor: "#FFFFFF",
    placeholder: "e.g. https://stackoverflow.com/users/123456/john-doe",
    urlPattern:
      /^https:\/\/(www\.)?stackoverflow\.com\/users\/\d+\/[A-Za-z0-9_.-]+\/?$/,
    errorMessage: "Must be a valid Stack Overflow profile URL",
  },
};
